export interface Product {
  id: string
  name: string
  category: string
  categorySlug: string
  price: number
  description: string
  shortDescription: string
  image: string
  specs: { label: string; value: string }[]
  tags: string[]
  featured?: boolean
}

export const categories = [
  { name: 'Barras', slug: 'barras', description: 'Barras de PRFV de alta resistencia para refuerzo estructural' },
  { name: 'Mallas', slug: 'mallas', description: 'Mallas de fibra de vidrio para aplicaciones de refuerzo' },
  { name: 'Perfiles', slug: 'perfiles', description: 'Perfiles estructurales en L, U, T y C para construcción industrial' },
  { name: 'Cercas y Barandillas', slug: 'cercas-barandillas', description: 'Sistemas de cerramiento y protección en PRFV' },
  { name: 'Rejillas', slug: 'rejillas', description: 'Rejillas industriales para plataformas y pasarelas' },
  { name: 'Conectores', slug: 'conectores', description: 'Conectores y accesorios para sistemas PRFV' },
  { name: 'Canales', slug: 'canales', description: 'Canales de drenaje y conducción en fibra de vidrio' },
  { name: 'Tubos Cuadrados', slug: 'tubos-cuadrados', description: 'Tubos de sección cuadrada en PRFV' },
  { name: 'Tubos Redondos', slug: 'tubos-redondos', description: 'Tubería redonda de PRFV para múltiples aplicaciones' },
  { name: 'Vara', slug: 'vara', description: 'Varas y bastones de fibra de vidrio' },
  { name: 'Uniones', slug: 'uniones', description: 'Piezas de unión y acoplamiento para tuberías PRFV' },
  { name: 'Bandeja Portacables', slug: 'bandeja-portacables', description: 'Bandejas portacables en PRFV para instalaciones eléctricas' },
  { name: 'Montaje Fotovoltaico', slug: 'montaje-fotovoltaico', description: 'Sistemas de montaje para paneles solares en PRFV' },
  { name: 'Tubo PRFV Mandril', slug: 'tubo-prfv-mandril', description: 'Tubo PRFV con mandril de avance continuo' },
  { name: 'Tubo PRFV Ascenso', slug: 'tubo-prfv-ascenso', description: 'Tubo PRFV de ascenso en plástico reforzado' },
  { name: 'Tubería Revestimiento', slug: 'tuberia-revestimiento', description: 'Tubería de revestimiento PRFV para pozos y perforaciones' },
  { name: 'Soluciones Sin Zanja', slug: 'soluciones-sin-zanja', description: 'Soluciones sin zanja para redes de agua potable y saneamiento' },
]

export const products: Product[] = [
  {
    id: 'barra-6mm',
    name: 'Barra PRFV Ø6mm',
    category: 'Barras',
    categorySlug: 'barras',
    price: 12.50,
    shortDescription: 'Barra de refuerzo PRFV de 6mm, ideal para construcción ligera.',
    description: 'Barra de Polímero Reforzado con Fibra de Vidrio de 6mm de diámetro. Ofrece una excelente relación resistencia/peso, resistente a la corrosión y con bajo peso específico. Ideal para estructuras de hormigón en entornos agresivos.',
    image: '/images/product-barras.jpg',
    specs: [
      { label: 'Diámetro', value: '6 mm' },
      { label: 'Longitud estándar', value: '6 m' },
      { label: 'Resistencia a tracción', value: '≥ 800 MPa' },
      { label: 'Módulo elástico', value: '45 GPa' },
      { label: 'Peso', value: '0.06 kg/m' },
    ],
    tags: ['refuerzo', 'construcción', 'corrosión'],
    featured: true,
  },
  {
    id: 'barra-12mm',
    name: 'Barra PRFV Ø12mm',
    category: 'Barras',
    categorySlug: 'barras',
    price: 28.00,
    shortDescription: 'Barra de refuerzo estructural PRFV de 12mm.',
    description: 'Barra PRFV de 12mm para aplicaciones estructurales exigentes. Óptima para refuerzo de pilotes, muros y losas en ambientes marinos o químicamente agresivos.',
    image: '/images/product-barras.jpg',
    specs: [
      { label: 'Diámetro', value: '12 mm' },
      { label: 'Longitud estándar', value: '6 m' },
      { label: 'Resistencia a tracción', value: '≥ 700 MPa' },
      { label: 'Módulo elástico', value: '45 GPa' },
      { label: 'Peso', value: '0.24 kg/m' },
    ],
    tags: ['refuerzo', 'estructural', 'marina'],
    featured: true,
  },
  {
    id: 'malla-100x100',
    name: 'Malla PRFV 100×100mm',
    category: 'Mallas',
    categorySlug: 'mallas',
    price: 45.00,
    shortDescription: 'Malla de refuerzo PRFV para hormigón proyectado.',
    description: 'Malla de fibra de vidrio con retícula de 100×100mm. Perfecta para refuerzo de taludes, túneles y revestimientos de hormigón. No corroe y no interfiere con las señales electromagnéticas.',
    image: '/images/product-mallas.jpg',
    specs: [
      { label: 'Luz de malla', value: '100×100 mm' },
      { label: 'Diámetro hilo', value: '5 mm' },
      { label: 'Peso por m²', value: '1.2 kg/m²' },
      { label: 'Formato', value: 'Rollo 1m × 50m' },
    ],
    tags: ['malla', 'hormigón', 'taludes'],
    featured: true,
  },
  {
    id: 'perfil-l-50x50',
    name: 'Perfil L PRFV 50×50mm',
    category: 'Perfiles',
    categorySlug: 'perfiles',
    price: 18.90,
    shortDescription: 'Perfil angular L de 50×50mm para estructuras industriales.',
    description: 'Perfil estructural en L de 50×50mm. Fabricado por pultrusión con resinas isoftálicas y fibra de vidrio continua. Resistente a corrosión, impacto y cargas dinámicas. Disponible en múltiples colores.',
    image: '/images/product-perfiles.jpg',
    specs: [
      { label: 'Sección', value: '50×50×5 mm' },
      { label: 'Longitud estándar', value: '6 m' },
      { label: 'Resistencia compresión', value: '200 MPa' },
      { label: 'Temperatura máx.', value: '80 °C' },
    ],
    tags: ['angular', 'perfil', 'estructural'],
    featured: true,
  },
  {
    id: 'rejilla-38x38',
    name: 'Rejilla Moldeada 38×38mm',
    category: 'Rejillas',
    categorySlug: 'rejillas',
    price: 89.00,
    shortDescription: 'Rejilla PRFV moldeada de alto tráfico, 38×38mm.',
    description: 'Rejilla de PRFV fabricada por moldeo con bidireccional de fibra. Retícula de 38×38mm. Ideal para plataformas offshore, pasarelas industriales, tratamiento de aguas y suelos.',
    image: '/images/product-rejillas.jpg',
    specs: [
      { label: 'Luz de malla', value: '38×38 mm' },
      { label: 'Altura panel', value: '25 mm' },
      { label: 'Módulo', value: '1000×3000 mm' },
      { label: 'Carga distribuida', value: '2.5 kN/m²' },
    ],
    tags: ['rejilla', 'plataforma', 'pasarela'],
    featured: true,
  },
  {
    id: 'tubo-redondo-dn50',
    name: 'Tubo Redondo PRFV DN50',
    category: 'Tubos Redondos',
    categorySlug: 'tubos-redondos',
    price: 22.50,
    shortDescription: 'Tubo redondo pultruído DN50 para conducción fluidos.',
    description: 'Tubo circular de PRFV fabricado por pultrusión. DN50 para sistemas de conducción de fluidos corrosivos, instalaciones eléctricas y estructuras ligeras.',
    image: '/images/product-tubos.jpg',
    specs: [
      { label: 'Diámetro exterior', value: '50 mm' },
      { label: 'Espesor pared', value: '3 mm' },
      { label: 'Longitud estándar', value: '6 m' },
      { label: 'Presión de trabajo', value: '6 bar' },
    ],
    tags: ['tubo', 'conducción', 'fluidos'],
    featured: true,
  },
  {
    id: 'cerca-modular',
    name: 'Sistema de Cerca Modular PRFV',
    category: 'Cercas y Barandillas',
    categorySlug: 'cercas-barandillas',
    price: 145.00,
    shortDescription: 'Panel de cerca modular para perímetros industriales.',
    description: 'Sistema modular de cerramiento en PRFV. Paneles de 2m×1.2m compatibles con postes y herrajes del mismo sistema. Sin mantenimiento, resistente a la corrosión, UV y cargas de viento.',
    image: '/images/product-cercas.jpg',
    specs: [
      { label: 'Dimensiones panel', value: '2000×1200 mm' },
      { label: 'Diámetro varilla', value: '10 mm' },
      { label: 'Resistencia UV', value: 'Clase 1' },
      { label: 'Color estándar', value: 'Verde / Gris / Amarillo' },
    ],
    tags: ['cerca', 'cerramiento', 'perimetral'],
    featured: false,
  },
  {
    id: 'bandeja-portacables-100',
    name: 'Bandeja Portacables 100mm',
    category: 'Bandeja Portacables',
    categorySlug: 'bandeja-portacables',
    price: 32.00,
    shortDescription: 'Bandeja portacables de 100mm, no conductora.',
    description: 'Bandeja portacables de PRFV, electricamente no conductora y resistente a la corrosión. Ideal para instalaciones en entornos agresivos, offshore y plantas petroquímicas.',
    image: '/images/product-bandeja.jpg',
    specs: [
      { label: 'Ancho', value: '100 mm' },
      { label: 'Alto', value: '60 mm' },
      { label: 'Longitud', value: '3000 mm' },
      { label: 'Carga máx.', value: '50 kg/m' },
    ],
    tags: ['cable tray', 'eléctrico', 'offshore'],
    featured: false,
  },
  {
    id: 'montaje-fotovoltaico-kit',
    name: 'Kit Montaje Fotovoltaico PRFV',
    category: 'Montaje Fotovoltaico',
    categorySlug: 'montaje-fotovoltaico',
    price: 320.00,
    shortDescription: 'Sistema completo de montaje solar en PRFV sin mantenimiento.',
    description: 'Kit completo de estructura de montaje para paneles fotovoltaicos fabricado en PRFV. Cero corrosión, sin necesidad de mantenimiento, no interfiere con sistemas de seguimiento. Compatible con paneles estándar de 60, 72 y 96 células.',
    image: '/images/sector-energia.jpg',
    specs: [
      { label: 'Material', value: 'PRFV isoftálico' },
      { label: 'Capacidad', value: 'Hasta 6 paneles por kit' },
      { label: 'Ángulo ajustable', value: '15° – 35°' },
      { label: 'Vida útil', value: '> 30 años' },
    ],
    tags: ['solar', 'fotovoltaico', 'energía'],
    featured: true,
  },
  {
    id: 'tubo-prfv-mandril',
    name: 'Tubo PRFV Mandril Avance Continuo',
    category: 'Tubo PRFV Mandril',
    categorySlug: 'tubo-prfv-mandril',
    price: 85.00,
    shortDescription: 'Tubo PRFV fabricado por arrollamiento filamentario continuo.',
    description: 'Tubo de gran diámetro fabricado por la técnica de mandril de avance continuo. Altamente resistente a la presión interna y a la corrosión química. Empleado en instalaciones de saneamiento, riego y conducción industrial.',
    image: '/images/product-tubos.jpg',
    specs: [
      { label: 'Diámetros', value: 'DN200 – DN3000' },
      { label: 'Presión nominal', value: 'PN0.5 – PN25' },
      { label: 'Rigidez anular', value: 'SN2500 – SN10000' },
      { label: 'Norma', value: 'ISO 10639' },
    ],
    tags: ['tubo grande', 'saneamiento', 'riego'],
    featured: true,
  },
  {
    id: 'solucion-sin-zanja',
    name: 'Solución Sin Zanja PRFV',
    category: 'Soluciones Sin Zanja',
    categorySlug: 'soluciones-sin-zanja',
    price: 0,
    shortDescription: 'Rehabilitación de redes de agua sin necesidad de excavación.',
    description: 'Sistema sin zanja para renovación y revestimiento de conducciones de agua potable y saneamiento. Minimiza la afección al tráfico y reduce los costes de obra. Compatible con tuberías existentes de cualquier material.',
    image: '/images/gallery-3.jpg',
    specs: [
      { label: 'Método', value: 'Slip lining / CIPP' },
      { label: 'Diámetros', value: 'DN100 – DN1200' },
      { label: 'Temperatura de trabajo', value: '-30 °C a +70 °C' },
      { label: 'Vida útil', value: '> 50 años' },
    ],
    tags: ['sin zanja', 'agua', 'rehabilitación'],
    featured: false,
  },
]
